version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: job_offer_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-alpine
    container_name: job_offer_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

volumes:
  postgres-data:
