version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postg
    environment:
      POSTGRES_DB: job_offer_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5433:5432"  # Make sure PostgreSQL default port is exposed correctly
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: offers_app
    depends_on:
      - postgres
    ports:
      - "8085:8080"  # Match your Spring Boot application's default port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

volumes:
  postgres-data:
