name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-config-server:
    name: Build Config Server Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution : 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
        working-directory: .

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/job-server:latest

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/job-server:latest
  #build-and-push:
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout code
        uses: actions/checkout@v2

      #- name: Log in to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKER_HUB_USERNAME }}
          #password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #- name: Build and tag Docker image
        #run: |
          #docker build -t job-offer-management:latest .
          #docker tag job-offer-management:latest sosouca/joboffer-management:latest

      #- name: Push Docker image to Docker Hub
        #run: |
          #docker push sosouca/joboffer-management:latest
